print
    sc_value_repr
        spice-quote
            """""eeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeöeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"

'() == '(1 2 3)

;
