
using import Capture

do
    # immutable capture

    let a = 10
    let b = 20

    @@ report
    capture cf (u v) {a b}
        print a b u v
        + a b u v

    fn testf (f)
        assert ((f 1 2) == (+ 10 20 1 2))

    testf cf

let T = (array.type i32 16)
spice-capture f () {T}
    dump T
    `(nullof T)

run-stage;

print (f)

# conditional capture generated by function
fn make (s a b)
    if s
        'typify
            capture "cf1" (u v) {a b}
                print a b u v
                + a b u v
            \ i32 i32
    else
        'typify
            capture "cf2" (u v) {a b}
                print a b u v
                - (+ a b u v)
            \ i32 i32

let cf = (make true 10 20)
assert ((cf 1 2) == (+ 10 20 1 2))
let cf = (make false 10 20)
assert ((cf 1 2) == (- (+ 10 20 1 2)))
