print
    sc_value_repr
        spice-quote
            """""eeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeöeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeöeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
