
using import testing

test-modules
    .test_abi
    .test_ansi_colors
    .test_any
    .test_array
    .test_branch
    .test_assorted
    .test_call_override
    .test_callback
    .test_capture
    .test_clang
    .test_closure
    .test_conversion
    .test_defer
    .test_dispatch
    .test_docstring
    .test_dots
    .test_enums
    .test_extraparams
    .test_fnchain
    .test_folding
    .test_frame
    .test_from
    .test_fwdecl
    .test_glm
    .test_glsl
    .test_inline
    .test_inplace_arithmetic
    .test_intrinsics
    .test_iter2
    .test_let
    .test_locals
    .test_loop
    .test_macro
    .test_match
    .test_memoization
    .test_merge
    .test_mutarray
    .test_namedargs
    .test_object
    .test_operators
    .test_overload
    .test_parser
    .test_quality
    .test_recursion
    .test_reference
    .test_regexp
    .test_scope_iter
    .test_scope
    .test_semicolon
    .test_spirv_loop
    .test_static
    .test_string
    .test_struct
    .test_submod
    .test_testing
    .test_tuple_array
    .test_union
    .test_using
    .test_varargs
    .test_vector
    .test_while
    .test_xpcall

