
using import testing

test-modules
    .test_abi
    .test_abs
    .test_alignment
    .test_anchor
    .test_ansi_colors
    .test_array
    .test_ast_quote
    .test_atomic
    .test_bool
    .test_box
    .test_branch
    .test_assorted
    .test_borrowing
    .test_callback
    .test_capture
    .test_clang
    .test_closure
    .test_codegen
    .test_conversion
    .test_convert
    .test_copy
    .test_currying
    .test_decorator
    .test_defer
    .test_dispatch
    .test_docstring
    .test_dots
    .test_embed
    .test_escaping
    .test_enums
    .test_extraparams
    .test_feature_matrix
    .test_fnchain
    .test_folding
    .test_forward
    .test_frame
    .test_from
    .test_fwdecl
    .test_glm
    .test_global
    .test_glsl
    .test_hash
    .test_iching
    .test_import
    .test_inline
    .test_inplace_arithmetic
    .test_intrinsics
    .test_iter2
    .test_itertools
    .test_label
    .test_let
    .test_local
    .test_locals
    .test_loop
    .test_macro
    .test_map
    .test_match
    .test_memoization
    .test_memory
    .test_mutarray
    .test_namedargs
    .test_object
    .test_operators
    .test_option
    .test_overload
    .test_parser
    .test_pointer
    .test_property
    .test_quote
    .test_rc
    .test_recursion
    .test_reference
    .test_regexp
    .test_scope_iter
    .test_scope
    .test_semicolon
    .test_spice
    .test_spice_attrib
    .test_spirv_loop
    .test_string
    .test_struct
    .test_sugar
    .test_switch
    .test_testing
    .test_try
    .test_tuple_array
    .test_typecast
    .test_typedef
    .test_typed_symbol
    .test_union
    .test_using
    .test_utf8
    .test_value
    .test_varargs
    .test_vector
    .test_wasm
    .test_while
